### ISSUE TITLE
Retrieving VRG from MCV is returning NotFound error where the object exists

### ISSUE THREAD

**Issue by BenamarMk** [RamenDR/ramen#95] opened 2021-07-07 18:53 UTC
getVRGFromManagedCluster is not behaving as expected.  The VRG exists in the managed cluster, but the error returned is NotFound.

**Comment by ShyamsundarR** [comment] 2021-08-16 18:11
@BenamarMk This is resolved post changes to condition checks for MCV?

**Comment by ShyamsundarR** [comment] 2021-09-09 17:08
Possibly linked to https://github.com/RamenDR/ramen/issues/254 as well

**Comment by ShyamsundarR** [comment] 2021-09-27 11:34
Closing this as #254 is also root caused.

**Closed by ShyamsundarR** 2021-09-27 11:34 UTC
Labels: bug, priority-1
